### ISSUE TITLE
Issue with parameter handling

### ISSUE THREAD

**Issue by BeilerOl** [JohnOmernik/sqlalchemy-drill#14]
Hello.

First, thanks a lot for your work :)

I try to use your SQLALchemy plugin to connect to Superset (new name of Caravel) and I encounter a series of issues when runing the tests which seem linked to parameter injection. For example, for the BooleanTest, I have the following error from MapR ODBC Driver :

> DBAPIError: (pyodbc.Error) ('HY000', '[HY000] [MapR][Drill] (1040) Drill failed to execute the query: select * from ? limit 0\n[30029]Query execution error. Details:[ \nPARSE ERROR: Encountered "?" at line 1, column 30.\nWas expecting one of:\n    <IDENTIFIER> ...\n    <QUOTED_IDENTIFIER> ...\n    <BACK_QUOTED_IDENTIFIER> ...\n    <BRACKET_QUOTED_IDENTIFIER> ...\n    <UNICODE_QUOTED_IDENTIFIER> ...\n    "LATERAL" ...\n    "(" ...\n    "UNNEST" ...\n    "TABLE" ...\n    \n\nSQL Query SELECT * FROM (select * from ? limit 0) LIMIT 0\n                             ^\n\n\n[Error Id: d2a36611-ba31-4123-ba17-a1b04374f310 on slave02:31010]\n] (1040) (SQLPrepare)') [SQL: 'select * from ? limit 0'] [parameters: ('boolean_table',)]

After doing more tests, it seems it comes from pyodbc queries not managing parameters. Here is my test code:

```
import pyodbc

# Connection example: with a DSN
cnxn = pyodbc.connect('DSN=SampleMapRDrillDSN64',autocommit=True)

# Opening a cursor
cursor = cnxn.cursor()

# Query without parameter -> it's working
cursor.execute("SELECT * FROM cp.`employee.json` WHERE salary>20000")
rows = cursor.fetchall()
for row in rows:
    if row:
        print(row)

# Query with parameter -> it's not working
cursor.execute("SELECT * FROM cp.`employee.json` WHERE salary>?",[20000])
rows = cursor.fetchall()
for row in rows:
    if row:
        print(row)
```

I was wondering if you ever encountered this issue. I use HBase v1.2.3, Drill v1.9.0, MapR ODBC v1.2.6 and v1.3.0 (both fail), pyodbc v3.1.1 and Superset v0.15.0.

Best,
Olivier

**Comment by cgivre** [comment]
Hi Oliver, 
I encountered a lot of issues getting this to work as well.  I've been working on a SQLAlchemy dialect for PyDrill and have gotten it to work with Superset.  
Here's the code so far:
https://github.com/cgivre/sqlalchemy-drill/tree/pydrill

With that said, it depends on a PyDrill DBAPI extension which I haven't posted yet.

**Comment by JohnOmernik** [comment]
Yes, I have not had the time to come back to this work as of late, I would
go with Charles' approach as things have moved on since I first attempted
this.

**Comment by BeilerOl** [comment]
Thanks a lot guys for your answer. I'll try your approach, Charles. Do you plan to post the PyDrill DBAPI soon?

**Comment by cgivre** [comment]
@BeilerOl I am going to post the DBAPI soon.  I need to put some finishing touches on it.

**Comment by BeilerOl** [comment]
Thanks :)

**Comment by cgivre** [comment]
Hi @BeilerOl 
I posted the DBAPI here:  https://github.com/airbnb/superset/issues/1993

**Comment by cgivre** [comment]
I think this has been fixed.
