### ISSUE TITLE
Which package is better to use today: sadrill or sqlalchemy-drill?

### ISSUE THREAD

**Issue by slattery** [JohnOmernik/sqlalchemy-drill#17]
Thank you John and @cgivre and everyone who is working on this.     Can you please tell me which package to start with if we are mostly planning to drill into CSV files?  I am anticipating using superset with types VARCHAR, FLOAT, INT, DATE and TIMESTAMP, but I can use the timestamps as categorical strings initially.    

Your work is a big help, and gives us a great chance to choose superset or redash based on user pref rather than format.  Cheers.

**Comment by JohnOmernik** [comment]
I have been using sadrill 

https://github.com/JohnOmernik/sadrill

Based on my own updates, it looks like that may be the better one. One would think I would know better, but I am a scatterbrain that moves around on projects around. Try sadrill first :)

**Comment by slattery** [comment]
Thank you!
