### ISSUE TITLE
Error in sqlalchemy_drill setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

### ISSUE THREAD

**Issue by ens-long-nguyen** [JohnOmernik/sqlalchemy-drill#30]
I get error when running the command: `python3 setup.py install`

> error in sqlalchemy_drill setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

**Comment by aksakalli** [comment]
I created a PR #31 to fix it, it works for my fork:

```bash
pip install git+https://github.com/aksakalli/sqlalchemy-drill.git@patch-2#egg=sqlalchemy_drill[jdbc]
```

**Comment by aksakalli** [comment]
The PR was merged, it should just work fine. You may close this issue.

**Comment by ens-long-nguyen** [comment]
> The PR was merged, it should just work fine. You may close this issue.

Yep, thz.
