### ISSUE TITLE
If Schema is not set, get tables fail with obscure error

### ISSUE THREAD

**Issue by JohnOmernik** [JohnOmernik/sqlalchemy-drill#4]
Drill requires you to set a schema. Should we try to catch ODBC connections that don't set schema prior to adding a database? Perhaps use a default schema? Options/thoughts?

**Comment by coderfender** [comment]
Yes. I understand that this is a three year old comment but I guess we need to provide this option so that apache superset table addition wouldn't fail.

**Comment by amilamanoj** [comment]
@coderfender Is this issue related to this? https://github.com/apache/superset/issues/14930
