### ISSUE TITLE
Can the author publish a PYPI package

### ISSUE THREAD

**Issue by mistercrunch** [JohnOmernik/sqlalchemy-drill#43]
Relate: https://github.com/apache/incubator-superset/pull/10407

**Comment by blcksrx** [comment]
Actually the drill SQL dialectic is not maintaining anymore and it's a too old repository. I think there is a reason behind that they didn't publish it on the `PyPI`. Anyway, we have two approaches:

1. Contact the drill SQL dialectic and try to convince them to publish it
2. Publish it by ourselves

**Comment by cgivre** [comment]
@mistercrunch 
We'll publish this to Pypi and update the Superset docs.  We've been meaning to for some time now. 
Thanks.

**Comment by blcksrx** [comment]
@cgivre I'm waiting for you guys

**Comment by cgivre** [comment]
@blcksrx @mistercrunch 
The dialect is now available on Pypi with the following command:

`pip install sqlalchemy-drill`

Here's the direct link: https://pypi.org/manage/project/sqlalchemy-drill/releases/
