### ISSUE TITLE
"Caught StopIteration in fetchone" after iterating results

### ISSUE THREAD

**Issue by gdubya** [JohnOmernik/sqlalchemy-drill#51]
I'm executing a statement on the Drill connection and then iterating over the results, and the "Caught StopIteration" text is bring printed out at the end of the iteration (see fetchone method). Can this be changed to logging.debug instead of print? Or am I using sqlalchemy incorrectly?

```
with engine.connect() as con:
    rs = con.execute("select * from az.`myfile.csv`")
    for row in rs:
        print(row)
```

**Comment by cgivre** [comment]
Fixed in https://github.com/JohnOmernik/sqlalchemy-drill/pull/52
