### ISSUE TITLE
Apache Superset - Query in SQL Lab works fine but unable to create Dataset from sqlalchemy-drill connection string

### ISSUE THREAD

**Issue by exwhyz** [JohnOmernik/sqlalchemy-drill#61]
Environment description:
Kernel: Linux DESKTOPXXX 5.4.72-microsoft-standard-WSL2
Distribution: Ubuntu 20.04.2 LTS (Focal Fossa)
Python 3.8.5
Apache Superset 1.0.1
Drill 1.18.0

I have successfully connected Apache Superset to Apache Drill using the sqlalchemy-drill DBAPI connection string. I can also run queries in SQL Lab without any problem. However if I try to create a Dataset in Apache Superset I am unable to do so. Also if I try to expand the Table connected to in Apache Superset SQL Lab I get errors while fetching table metadata. Stack trace from Apache Superset console is below:

> ERROR:root:module 'sqlalchemy_drill.drilldbapi' has no attribute 'Error'
> Traceback (most recent call last):
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
>     self.dialect.do_execute(
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
>     cursor.execute(statement, parameters)
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy_drill/drilldbapi/_drilldbapi.py", line 65, in func_wrapper
>     return func(self, *args, **kwargs)
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy_drill/drilldbapi/_drilldbapi.py", line 165, in execute
>     elif str(df[col_name].iloc[0]).startswith("[") and str(df[col_name].iloc[0]).endswith("]"):
>   File "/home/hum/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 879, in __getitem__
>     return self._getitem_axis(maybe_callable, axis=axis)
>   File "/home/hum/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1496, in _getitem_axis
>     self._validate_integer(key, axis)
>   File "/home/hum/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1437, in _validate_integer
>     raise IndexError("single positional indexer is out-of-bounds")
> IndexError: single positional indexer is out-of-bounds
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/hum/venv/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 84, in wraps
>     return f(self, *args, **kwargs)
>   File "/home/hum/venv/lib/python3.8/site-packages/superset/views/base_api.py", line 79, in wraps
>     duration, response = time_function(f, self, *args, **kwargs)
>   File "/home/hum/venv/lib/python3.8/site-packages/superset/utils/core.py", line 1289, in time_function
>     response = func(*args, **kwargs)
>   File "/home/hum/venv/lib/python3.8/site-packages/superset/utils/log.py", line 164, in wrapper
>     value = f(*args, **kwargs)
>   File "/home/hum/venv/lib/python3.8/site-packages/superset/datasets/api.py", line 233, in post
>     new_model = CreateDatasetCommand(g.user, item).run()
>   File "/home/hum/venv/lib/python3.8/site-packages/superset/datasets/commands/create.py", line 47, in run
>     self.validate()
>   File "/home/hum/venv/lib/python3.8/site-packages/superset/datasets/commands/create.py", line 87, in validate
>     if database and not DatasetDAO.validate_table_exists(
>   File "/home/hum/venv/lib/python3.8/site-packages/superset/datasets/dao.py", line 81, in validate_table_exists
>     database.get_table(table_name, schema=schema)
>   File "/home/hum/venv/lib/python3.8/site-packages/superset/models/core.py", line 604, in get_table
>     return Table(
>   File "<string>", line 2, in __new__
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
>     return fn(*args, **kwargs)
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 563, in __new__
>     metadata._remove_table(name, schema)
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
>     compat.raise_(
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 558, in __new__
>     table._init(name, metadata, *args, **kw)
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 647, in _init
>     self._autoload(
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 670, in _autoload
>     autoload_with.run_callable(
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2212, in run_callable
>     return conn.run_callable(callable_, *args, **kwargs)
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1653, in run_callable
>     return callable_(self, *args, **kwargs)
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 484, in reflecttable
>     return insp.reflecttable(
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 664, in reflecttable
>     for col_d in self.get_columns(
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 390, in get_columns
>     col_defs = self.dialect.get_columns(
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy_drill/base.py", line 382, in get_columns
>     views = self.get_view_names(connection, schema)
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy_drill/base.py", line 337, in get_view_names
>     curs = connection.execute("SELECT `TABLE_NAME` FROM INFORMATION_SCHEMA.views WHERE table_schema='" + schema + "'")
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
>     return self._execute_text(object_, multiparams, params)
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
>     ret = self._execute_context(
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
>     self._handle_dbapi_exception(
>   File "/home/hum/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1390, in _handle_dbapi_exception
>     isinstance(e, self.dialect.dbapi.Error)
> AttributeError: module 'sqlalchemy_drill.drilldbapi' has no attribute 'Error'

**Comment by iercan** [comment]
@exwhyz I send a PR I believe it also resolve this issue.

**Comment by exwhyz** [comment]
Hi @iercan 

I can confirm that this resolves the issue after updating it with the suggested change in the PR. Apache Superset is now able to create the dataset as well as browse the metadata in the SQL Lab. Thanks!
