### ISSUE TITLE
Do a PyPI release (not a pre-release)

### ISSUE THREAD

**Issue by jnturton** [JohnOmernik/sqlalchemy-drill#63]
Hi.  So far only pre-releases have been shipped to PyPI:

https://pypi.org/project/sqlalchemy-drill/#history

but this project seems decidedly stable and I would like to use it as a dependency in a PR to add an Apache Drill provider to Apache Airflow.  I strongly suspect that the Airflow reviewers will not accept my PR with `sqlalchemy-drill>=0.3.dev0` listed as a requirement.

So, can you ship a sqlalchemy-drill 0.3.0 to PyPI?

Thanks
James

**Comment by jnturton** [comment]
@cgivre please see #68

**Comment by cgivre** [comment]
I just uploaded version 1.0 to Pypi.
