### ISSUE TITLE
GitHub's release for latest version 1.1.1

### ISSUE THREAD

**Issue by FraPazGal** [JohnOmernik/sqlalchemy-drill#72]
Hello all,

I saw that version `1.1.1` is already released in [PyPI](https://pypi.org/project/sqlalchemy-drill/1.1.1/) but there is no such released version with the source code here in GH. I just wanted to ask if it is planned to make said release or if it is a conscious decision, a consequence of a change in your Release Policy.

Regards,
Francisco de Paz

**Comment by jnturton** [comment]
I'm pretty sure it was just an oversight... @cgivre?

The HEAD of the master branch now (2d608461749384ca97e1ace23a3da0d8ef9ad4fa) still corresponds with the 1.1.1 release if you're after the source.

**Comment by cgivre** [comment]
Yeah, I can add it.  I didn't really know how important that was.  I kind of figured that since you can get the latest version from github as well as pypi, the github release wasn't as important.

**Comment by cgivre** [comment]
Done.
