### ISSUE TITLE
cannot connect to drill

### ISSUE THREAD

**Issue by hhhss91** [JohnOmernik/sqlalchemy-drill#80]
Hi, I have a trouble making connection with drill. 
I think the problem is same as explained in this thread https://github.com/JohnOmernik/sqlalchemy-drill/issues/70. So, I reinstalled the version of drill to 1.19 and installed sqlalchemy 1.1 by stating sqlalchemy==1.1 in my requirement package. I will attache an image and error log to help you understand better. Thank you!
```superset.databases.commands.exceptions.DatabaseTestConnectionFailedError: [SupersetError(message='(builtins.NoneType) None\n(Background on this error at: https://sqlalche.me/e/14/dbapi)', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Apache Drill', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]```

![image](https://user-images.githubusercontent.com/13128340/196204048-c06bc262-91f0-4925-8466-272dbdd91320.png)

**Comment by jnturton** [comment]
Have you also got a storage plugin in Drill named "mongo", or why is that present in your URI? You can debug by testing from iPython using commands such as

```
In [1]: from sqlalchemy import create_engine
In [2]: engine = create_engine(
   ...:     URL.create(
   ...:         username='foo',
   ...:         password='bar',
   ...:         drivername='drill+sadrill',
   ...:         host='localhost',
   ...:         port=8047,
   ...:         database='dfs',
   ...:         query={'use_ssl': 'False'}
   ...:     ),
   ...:     pool_size=1,
   ...:     pool_recycle=20*60
   ...: )
 ```
 
I recommend using the most recent released versions of Drill and sqlalchemy-drill.
